title: Hacker-Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Albert Nafría"
  email: "albert.nafria@gmail.com"
  url: "https://albertnafria.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Albert Nafría"
year : "2020"
